### ISSUE TITLE
GitHub Actions - migrate linter, devops sanity check and v5 tests to github actions

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3675]
### Description

Migrate linter, devops sanity check and v5 tests to github actions, leaving only v4 backend test on travis

### Goals
- [x] v5 lint action
- [x] v5 tests action
- [x] devops sanity check action

### Tasks
- [x] TBD

**Comment by keifgwinn** [comment]
```
# make sure we're not merging DevOps changes
  devOpsSanityCheck:
    name: Ensure that custom settings are not being merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .azure/build-and-deploy.yaml
        uses: Bhacaz/checkout-files@v2
        with:
          files: .azure/build-and-deploy.yaml
          branch: ${{ github.head_ref || github.ref_name }}
      - name: Check to see if customHelmOverride has any APP settings
        id: customHelmOverride
        uses: mikefarah/yq@master
        with:
          cmd: if ( $(yq eval '.variables.customHelmOverride | ( contains("APP_") )' .azure/build-and-deploy.yaml) === "true" ); then echo $(yq eval '.variables.customHelmOverride' .azure/build-and-deploy.yaml); exit 1;  fi

```
